stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    params:
      - app/configs/unet_resnet.yaml:
        - TRAIN.seed
        - TRAIN.num_epoch
        - TRAIN.optim
        - MODEL.name
        - MODEL.encoder
    outs:
      - save/UNet
      - save/results.txt
  evaluate_val:
    cmd: python app/evaluate/eval_val.py
    deps:
      - app/evaluate/eval_val.py
      - save/UNet
      - save/results.txt
    outs:
      - save/val_plot.png
    metrics:
      - save/val_metrics.json:
          cache: false
  evaluate_test:
    cmd: python app/eval_test.py
    deps:
      - app/eval_test.py
      - save/UNet
    metrics:
      - save/test_metrics.json:
          cache: false