DATASET:
  root_dataset: "data/Kaggle_CT/"
  train_images: 'data/Kaggle_CT/images_radiopedia.npy'
  train_masks: 'data/Kaggle_CT/masks_radiopedia.npy'
  val_images: 'data/Kaggle_CT/images_medseg.npy'
  val_masks: 'data/Kaggle_CT/masks_medseg.npy'
  test_images: 'data/COVID19_1110/test/images.npy'
  test_masks: 'data/COVID19_1110/test/masks.npy'
  num_classes: 2
  num_channels: 1
  concatenate_class: True

MODEL:
  name: 'UNet'
  encoder: 'densenet201'

TRAIN:
  seed: 666
  num_epoch: 50
  batch_size: 8
  optim: "AdamW"